FROM alpine:3.8

# Install nginx
RUN apk add --update --no-cache nginx && \
    mkdir -p /run/nginx

# Add nginx config files
ADD nginx.conf          /etc/nginx/nginx.conf
ADD nginx-vhost.conf    /etc/nginx/sites-enabled/nginx-vhost.conf

# Add application code
ADD index.php /app/index.php

CMD [ "nginx", "-c", "/etc/nginx/nginx.conf" ]
